### PR TITLE
Correct Quarkus QE Beefy issue number

### PR DESCRIPTION
**Pull request by Sgitario**

### CODE REVIEW

**Comment by Sgitario** [comment]
Issue number: https://github.com/quarkusio/quarkus/issues/15417

**Comment by geoand** [comment]
Excellent 👌

**Comment by gsmet** [comment]
I added the issue here: https://status.quarkus.io/ . Hopefully, it will be green soon :).

**Comment by geoand** [comment]
Lovely, everything falls into place!

**Pull request merged**
