### PR TITLE
Add script to reclaim space

### PR DESCRIPTION
**Pull request by Sgitario**

### CODE REVIEW

**Comment by Sgitario** [comment]
cc @geoand

**Comment by geoand** [comment]
Thanks for this, but unfortunately the way you did the change won't affect CI participants.

To make it part of the CI participants workflow, you need to add it to https://github.com/quarkusio/quarkus-ecosystem-ci/blob/master/setup-and-test

**Comment by Sgitario** [comment]
> Thanks for this, but unfortunately the way you did the change won't affect CI participants.
> 
> To make it part of the CI participants workflow, you need to add the run of the script in https://github.com/quarkusio/quarkus-ecosystem-ci/blob/master/setup-and-test

Changed.

**Comment by Sgitario** [comment]
> Looks good! Just one question: is `ci-prerequisites.sh` executable?

Yes, it is. Should I add "#!/bin/bash" ?

**Comment by geoand** [comment]
No need, just wanted to make sure the file is executable.

Thanks

**Pull request merged**
