### PR TITLE
[Kogito] Disable Quarkus LTS branch

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Comment by geoand** [comment]
`2.6` is **not** going to be the base for the next product release. `2.7` is going to the base for that

**Comment by radtriste** [comment]
@geoand thx ! So disable until 2.7 is out.

**Review by geoand — APPROVED** [review]

**Comment by radtriste** [comment]
@geoand LTS is still executed. See https://github.com/kiegroup/kogito-runtimes/runs/4757323490?check_suite_focus=true

**Comment by radtriste** [comment]
nevermind, this is a problem on our side ... sorry for that ...

**Pull request merged**
