### PR TITLE
Remove Camel Quarkus from the Ecosystem CI

### PR DESCRIPTION
**Pull request by ppalaga**
This reverts commit 649378e8498f26c400ddfa79d0523c795117b03a.

### CODE REVIEW

**Comment by maxandersen** [comment]
@ppalaga how about updating this to refer to the camel issue you guys have and for now ignore the starring ? 

then we still have camel listed and with link to wherever your "tracking issue" is ?

**Comment by ppalaga** [comment]
I learned from @jamesnetherton yesterday that his pipeline opens each time a new issue and tags it with `build/quarkus-master`. Here is the list: https://github.com/apache/camel-quarkus/issues?q=+is%3Aissue+label%3Abuild%2Fquarkus-master

The current `camel-quarkus/info.yaml` points at my camel-quarkus fork, so it is not very useful anyway.

**Comment by gsmet** [comment]
I would really like us to keep it. Camel Quarkus is one of the most important part of the Platform and we need to be able to track its status properly.

Having the ecosystem CI consistent is important.

**Comment by gastaldi** [comment]
This is pointing to @ppalaga's fork, and he disabled issues in his repository, so I don't think this does what it's supposed to do :)

**Comment by gastaldi** [comment]
But yes, I agree with @gsmet that Camel Quarkus should use the Ecosystem CI - I think Camel was the primary driver for the Ecosystem CI to exist :)

**Pull request merged**
